# Generated by Django 5.2.7 on 2025-12-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_borrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'permissions': [('can_view_all_borrows', 'Can view all borrows')]},
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
